### ISSUE TITLE
Как ты решаешь задачи сложности hard?

### ISSUE THREAD

**Issue by tauke1** [lzakharov/hackerrank-interview-preparation-kit#1]
Привет! У меня никак не даются hard задачи, можешь дать совет как ты к ним готовился, какую литературу читал?

**Comment by lzakharov** [comment]
Привет, @tauke1!
Могу посоветовать несколько хороших книг, которые должны помочь (их конечно больше, но эти первыми приходят в голову):

- [Алгоритмы. Построение и анализ](https://www.ozon.ru/context/detail/id/33769775/)
- [The Algorithm Design Manual](http://www.algorist.com)
- [Cracking the Coding Interview: 189 Programming Questions and Solutions](https://www.amazon.com/Cracking-Coding-Interview-Programming-Questions/dp/0984782850)

Плюс отличный ресурс для тренировок: https://codeforces.com.

**Comment by tauke1** [comment]
Спасибо!
